apiVersion: v1
kind: Secret
metadata:
  name: kbs-auth-public-key
type: Opaque
data:
  publicKey: {{ .Files.Get "files/publicKey.b64" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: kbsres1
type: Opaque
stringData:
{{- range $key, $val := .Values.trustee.kbsres1 }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: security-policy
type: Opaque
stringData:
  osc: |
{{ .Values.trustee.policy | indent 4 }}
